# Generated by Django 3.1.5 on 2021-04-29 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0, null=True)),
                ('abtu', models.CharField(max_length=300)),
                ('typclass', models.CharField(max_length=20)),
                ('typconcession', models.CharField(choices=[('general', 'GENERAL'), ('ladies', 'LADIES'), ('tatkal', 'TATKAL'), ('premiumtatkal', 'PREMIUM TATKAL')], default='general', max_length=20)),
                ('roundtrip', models.BooleanField(default=False)),
                ('datefortrip', models.DateField(default=datetime.datetime.now)),
                ('images', models.ImageField(default='None', null=True, upload_to='pics')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
