# Generated by Django 3.2 on 2021-04-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='typclass',
            field=models.CharField(choices=[('DConcession', 'Divyaang Concession'), ('TWAB', 'Train with Available Berth')], default='DConcession', max_length=20),
        ),
    ]
