# Generated by Django 3.2 on 2021-04-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_booking_typclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='typclass',
            field=models.CharField(choices=[('Divyaang Concession', 'Divyaang Concession'), ('Train with Available Berth', 'Train with Available Berth')], default='Divyaang Concession', max_length=30),
        ),
    ]
