# Generated by Django 3.2 on 2021-05-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_booking_typclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
